[package]
name = "falcon-example-0"
version = "0.2.1"
authors = [ "Alex Eubanks <endeavor@rainbowsandpwnies.com>" ]
license = "Apache-2.0"

[dependencies]
clap = "2.26"
falcon = "0.2.1"

[[bin]]
name = "example-0"
path = "src/main.rs"